version: '3.9'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: build/server/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - db
    env_file:
      - .env
    command: go run main.go

  db:
    container_name: db
    build:
      context: .
      dockerfile: build/db/Dockerfile
    volumes:
      - type: volume
        source: sample_db_volume
        target: /var/lib/mysql
    env_file:
      - .env

volumes:
  sample_db_volume:
